# Introducción a Jupyter notebooks

Es una herramienta interactiva que nos permite ejecutar Python desde el navegador web. Ocuparemos esta herramienta a lo largo del curso, en el cual desarrollaremos rápidamente las habilidades necesarias para resolver problemas de ingeniería. No aprenderemos todo sobre programación, modelado matemático o todo tipo de problemas de ingeniería. El objetivo del curso es que sean capaces de pensar de una forma computacional para poder pasar de un problema a código y así poder aumentar nuestras habilidades analíticas. 

Todas estas notas estarán disponibles durante la clase. 

Objetivos de hoy:

- Explorar jupyter
- Practicar markdown
- Definir variables
- Crear arrays 

Hay dos tipos de celdas en los cuadernos de jupyter: Markdown y Code

## Markdown
Es un lenguaje de etiquetas diseñado para poder ser leído por humanos

Da doble click en esta celda para que puedas ver cómo lograr el siguiente output:

1. Crear
2. Una 
3. Lista 
4. Numerada

Otro tipo de lista:

- Con
- Puntitos
    - Con indexación
        - A diferentes
        - Niveles

Se puede agregar texto en **negritas**, *itálicas*, <del>tachado</del>, incluso <font color="red">rojo</font>
    
Para ecuaciones matemáticas podemos escribirlas en LaTeX ([https://en.wikibooks.org/wiki/LaTeX/Mathematics](https://en.wikibooks.org/wiki/LaTeX/Mathematics)).

Veamos:

- esto es una fracción $\frac{1}{4}$
- raíz cuadrada $\sqrt{564}$
- suma $\sum_{i=1}^{10} t_i$
- fórmula química H$_2$O
- una integral $\int_a^b f(x)dx$

Para crear títulos simplemente añade un $#$, con uno solo crearás un título principal, si añdaes más será un subtítulo y asi sucesivamente, ejemplo:
# Título
## Sub título
### Sub-sub título

---
Documentación completa:  [https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html).

---

No es necesario que aprendas esto ahora. Pero te recomiendo que documentes lo que hacemos de esta forma, así podrás volver a consultarlo en cualquier momento. 

Puedes convertir una celda a tipo markdown presionando Esc+m y regresar a tipo code con Esc+y


In [31]:


# las celdas de código se ejecutan con Ctrl+Enter
# para ejecutar y pasar a la siguiente celda Shift + Enter

Hola Mundo


## Ejecutando código

Los cuadernos de jupyter nos sirven para dos cosas:

1. Documentar nuestro trabajo
2. Ejecutar código de Python

Es importante saber cómo funcionan estos cuadernos de jupyter, en primera instancia podemos observar que se muestran en el navegador, el código no es ejecutado aquí sino que se envía a un servidor que en nuestro caso es nuestra propia computadora, una vez que termina la ejecución los resultados están de vuelta en el navegador. 



#### Concepto de variable:

Cúal es el valor de $a$ que satisface $a +15 = 32$?

Podemos agregar aquí toda la explicación al problema, despejar la ecuación:

$a = 32-15$

Se pueden editar las celdas de texto ya existentes dando doble click sobre ellas. Una vez que terminemos de editar solamente deberás presionar Ctrl+Enter para volver a renderizar la celda. 

Se muestra el código para la solución:

La solución es :17


17

19

Crea una celda de código que defina dos variable $x=3$  ,  $y=6$, y después realiza $x^2 + y^2$.

45

Podemos incertar nuevas celdas con las siguientes combinaciones:

- **Esc + a** Inserta una celda de código arriba (above)
- **Esc + b** Inserta una celda de código abajo (below)

Es muy importante el orden de ejecución de las celdas 

18

NameError: name 'b' is not defined

## Numpy

Es una librería muy potente para el manejo de arreglos, matrices multidimensionales.

- ``list`` no tiene un buen manejo para los indices cuando se trabajan matrices de mas de dos dimensiones

- ``list`` no posee métodos de algebra lineal, ni operaciones definidas

Numpy es parte de todo un ecosistema de librerias muy útiles que estaremos viendo durante el curso

La forma de importarla es la siguiente, tendremos que hacer esto siempre que queramos trabajar con ella:

Para ver la sección de "help" ejecuta la siguiente celda

## Crear arrays

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([[0., 0., 0.],
       [0., 0., 0.]])

array([[1., 1., 1.],
       [1., 1., 1.]])

<div class="alert alert-warning">
 np.linspace es una función que permite crear arrays de una dimensión, de largo n, y que contienen puntos entre a y b, distanciados de forma regular. La distancia entre cada punto sera de $(b-a)/(n-1)$.
</div> 

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

La gran mayoría de las operaciones matemáticas sobre arreglos son del tipo elemento a elemento

array([0.  , 0.01, 0.04, 0.09, 0.16, 0.25, 0.36, 0.49, 0.64, 0.81, 1.  ])

### Dimensión de un array

(11,)

array([[0., 0., 0.],
       [0., 0., 0.]])

(2, 3)

Podemos definir nuevas variables a partir de operaciones

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

(11,)

[0, 1, 2]
[0 1 2]


[0, 1, 2, 0, 1, 2]

array([0, 2, 4])

(3,)

(1, 3)

False

### Acceso a elementos y Slicing

array([[ 1,  0,  3],
       [ 4,  3,  5],
       [ 6, 10, -1]])

10

Para acceder a un elemento de un array de dimensión n, la síntaxis es $array[i1, i2, i3,...iN]$.
En este curso frecuentemente trabajaremos con arrays de dimensión 1 o dimensión 2, por lo que:

- Para un array de 1D: $a[index]$
- Para un array de 2D: $a[index1, index2]$

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([0, 1, 2, 3, 4])

array([0., 1., 0.])

array([0., 0., 1.])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Operaciones sobre arrays

a     = [0 1 2 3]
a + 5 = [5 6 7 8]
a - 5 = [-5 -4 -3 -2]
a * 2 = [0 2 4 6]
a / 2 = [0.  0.5 1.  1.5]
a // 2 = [0 0 1 1]
-a     =  [ 0 -1 -2 -3]
a ** 2 =  [0 1 4 9]
a % 2  =  [0 1 0 1]


Cuando ocupamos numpy arrays realmente no se ejecuta por ejemplo el operador de suma, sino que se llaman a las ufunc o universal functions, que trabajan sobre los mupy arrays y son muy rápidas. 

| operador | ufunc |
|------|------|
|   + | np.add|
|-|np.substract|
|* |np.multiply|
            
            

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

array([0.        , 0.69314718, 1.09861229, 1.38629436])

array([0.        , 1.        , 1.41421356, 1.73205081])

array([False, False, False, False])

array([0, 1, 2, 3])

array([1, 2, 3, 4])

## Rendimiento

Podrás preguntarte que pasa si por mi cuenta hago los algoritmos para que se ejecuten estas operaciones con tipos de datos nativos de python, que son las listas.

Por un lado las ufuncs corren a velocidad de un programa compilado en C, es decir muy rápido.
Al implementar las funciones deberíamos de usar los for loops.
Si ya están programadas y corren en C, la ventaja es muy grande. 
Un código Numpy con solamente funciones nativas, sin bucles, se le llama código vectorizado.

264 ms ± 6.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


2.46 ms ± 81.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# Funciones

Las funciones son utilizadas en cualquier lenguaje de programación, nos permiten reutilizar código, hacen que los programas sean más legibles. 

## Cómo definir una función

Se definen con la palbra reservada `def`, se debe especificar un nombre y los argumentos que reciben dentro de parentesis y terminar con el caracter de dos puntos `:`. 

El cuerpo de la función debe estar identado, normalmente con un tabulador (4 espacios), para terminar la función debemos de salir de la sangría de tabulador. Se debe especificar el valor de retorno de la función con la palabra reservada `return`

Ejemplo de una función que multiplica por dos el valor dado y lo regresa:

Ahora evaluemos la función con diferentes parámetros:

2
2.0
[0 2]
[0 2]


Siempre es bueno añadir documentación a nuestra función, lo haremos de la siguiente forma:

El argumento recibido es: 4, La operacion 8
El argumento recibido es: hola, La operacion holahola
El argumento recibido es: [0, 1, 2], La operacion [0, 1, 2, 0, 1, 2]
El argumento recibido es: [0 1 2], La operacion [0 2 4]


array([0, 2, 4])

TypeError: f1() missing 1 required positional argument: 'x'

### Funciones con múltiples argumentos

Que pasa si nuestra función debe recibir opcionalmente más parámetros, por ejemplo una función que reciba dos parámetros, $p$ y $q$, donde $q$ tiene el valor por default de 4. 

Evaluemos la función con diferentes parámetros

16

En la siguiente celda evaluamos la función con los parámetros $p=4$ y $q=2$ definidos

8

Podemos ser muy específicos a la hora de definir los variables que tienen un valor por default

12

Pero debemos tener cuidado con las variables que no tienen valor por default, ya que éstas adquieren su valor poscicionalmente, es decir, se asigna su valor en función de la posición que tiene en la definición de la función, ejemplo:

SyntaxError: positional argument follows keyword argument (<ipython-input-19-842a9523c4c1>, line 1)

A menos que definamos ambas variables explícitamente:

12

### Alcance de las variables

El alcance de las variables hace referencia a el lugar (en el código)  donde la variable fue definida y el valor que posee en ese momento. En el siguiente ejemplo evidenciaremos la importancia del nombramiento de variables, definición correcta de funciones. Ejemplificaremos con la variable `a`

4

90

Podemos asignar el valor de la variable `a` de forma local dentro de una función sin afectar el valor global de la otra variable `a`

(6, 2)

El valor de la variable `a` no ha cambiado

2

## Cadenas de texto 

Ocuparemos muchas veces la función $print$, veamos que podemos hacer con ella.

Resta de 34-23 es 11 añadiendo más texto separando con comas


La suma de 65 más 78 es 143. Mensaje extra


En este ejemplo ocupamos las cadenas con formato, con f'...', aquí los elementos que se encuentran entre llaves {} serán reemplazados con el valor de las variables. 

Nosotros a lo que aplicaremos el formato será a los números decimales, porque si lo imprimimos sin formato se mostrarán todos los decimales, ejemplo:

5064937.857142857


Asi que daremos formato acotando los decimales que mostraremos.

a = 5064937.8571


La sintáxis es {variable:separación.decimalesf}, hay diferentes opciones, dejo el link a la documentación [aquí](https://docs.python.org/3.6/library/string.html#format-specification-mini-language).
 

## Resumen

En este punto hemos estudiado lo siguiente:
- Markdown
- Ejecutar celdas de código   
- Crear Numpy arrays
- Definir funciones con argumentos
- Imprimir cadenas de texto con las varibles deseadas. 

La siguiente sesión:

Empezaremos a usar funciones para resolver integrales y ecuaciones diferenciales. 